### ISSUE TITLE
RSS Feed not working after beeing fine for 2 years

### ISSUE THREAD

**Issue by antonweber85** [w3c/feedvalidator#24]
https://www.presseportal.de/rss/dienststelle_104234.rss2

Can anyone tell me what i am doing wrong here to get the police news pulled and showed by my wordpress news page?

**Comment by dontcallmedom** [comment]
I've updated the feedvalidator so that it now checks this feed correctly.

That being said, www.pressportal.de is not configured correctly with SSL, using a week signature algorithm (SHA1) which will likely cause issues with other clients beyond the feed validator. I don't know if you have any contacts with presseportal.de, but they may want to look into this.

**Comment by antonweber85** [comment]
Thanks a lot mate!
