### ISSUE TITLE
Trouble verifying feed

### ISSUE THREAD

**Issue by user1029384734** [w3c/feedvalidator#44]
![1](https://user-images.githubusercontent.com/83780975/117340363-a514f780-ae55-11eb-84d2-95cf655b521a.JPG)

The main issue is that my RSS feed URL won't connect with Mailchimp when I'm trying to set up emails that go out when I post a blog post.

![2](https://user-images.githubusercontent.com/83780975/117340499-cd045b00-ae55-11eb-981d-8d3f41fe1113.JPG)

My host (Hostgator) says that everything is fine on their end with the SSL. What else could be the problem?

**Comment by dontcallmedom** [comment]
interesting - the problem doesn't seem to be on your side indeed; in fact, while this error happens on the online service, it doesn't happen when I run it on my machine, which means it's likely an issue with the server where the online feed validator runs.

My current suspicion is a bug in the python setup, which may coincidentally be also affecting mailchimp? or maybe a bug in a specific openssl version? I will let you know if I figure this out.

**Comment by dontcallmedom** [comment]
it turns out it is on your side after all - your web site is served through 3 servers (gator4239.hostgator.com, 107.154.158.227.ip.incapdns.net , 107.154.172.227.ip.incapdns.net ) and while indeed the hostgator server is correctly set up, the two others have an incomplete certificate chain which can make the retrieval fail in a number of tools.

See https://www.ssllabs.com/ssltest/analyze.html?d=thereandbackagainrv.com and https://www.ssllabs.com/ssltest/analyze.html?d=thereandbackagainrv.com&s=107.154.158.227

Because the problem is only on two of the 3 servers, it will only happen irregularly (which threw me off).
